@startuml

package Pipelines {

    class Trigger {
        table_names: List<String>
    }

    class DataSources_ReadData {
        table_name
        columns
        filters
    }

    class DataDestinations_CreateTable {
        table_name
        columns
    }

    class DataDestinations_InsertData {
        table_name
        columns
        filters
    }

    class Result {

    }

    Trigger -> DataSources_ReadData
    DataSources_ReadData -> DataDestinations_CreateTable
    DataSources_ReadData --> DataDestinations_InsertData
    DataDestinations_InsertData -> Result
}

@enduml


@startuml

package Pipelines {
    class Trigger {
        table_names
    }

    class PostgreSQL_ReadData {
        table_name
        period
    }

    class BigQuery_CreateTable {
        table_name
    }

    class BigQuery_InsertData {
        table_name
        columns
        filters
    }

    class Result {

    }

    Trigger -> PostgreSQL_ReadData
    PostgreSQL_ReadData -> BigQuery_CreateTable
    PostgreSQL_ReadData --> BigQuery_InsertData
    BigQuery_InsertData -> Result

}


@enduml